/* Fallback catalogue used when the backend API is unreachable, so the
   storefront is fully browsable as a static demo. Shape mirrors the
   Mongo Product model returned by GET /api/products. */

const img = (keywords, lock, w = 800, h = 1000) =>
  `https://loremflickr.com/${w}/${h}/${keywords}?lock=${lock}`;

const FALLBACK_PRODUCTS = [
  { _id: 'm1', name: 'Tailored Wool Overcoat', brand: 'Raymond', category: 'men', price: 6999, discountPercent: 15,
    description: 'A structured double-breasted overcoat cut from a heavyweight wool blend. Built for cold-weather layering without losing its silhouette.',
    images: ['https://images.pexels.com/photos/18726866/pexels-photo-18726866.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/34609625/pexels-photo-34609625.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['S','M','L','XL'], stock: 24, isFeatured: true, isTrending: true, rating: 4.7, numReviews: 3,
    reviews: [{name:'Ananya R.',rating:5,comment:'Fit is exactly as described, fabric feels genuinely premium.'},{name:'Rohan K.',rating:4,comment:'Great quality, runs slightly large so consider sizing down.'}] },
  { _id: 'm2', name: 'Merino Crewneck Sweater', brand: 'Allen Solly', category: 'men', price: 2499, discountPercent: 0,
    description: 'Fine-gauge merino wool knit with a clean crewneck finish, made for everyday layering.',
    images: ['https://images.pexels.com/photos/10614457/pexels-photo-10614457.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/9558897/pexels-photo-9558897.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['XS','S','M','L','XL'], stock: 40, isFeatured: true, isTrending: false, rating: 4.5, numReviews: 2,
    reviews: [{name:'Priya S.',rating:5,comment:'Ordered twice now, stitching and finish are consistently excellent.'}] },
  { _id: 'm3', name: 'Slim Selvedge Denim', brand: "Levi's", category: 'men', price: 3299, discountPercent: 0,
    description: 'Rigid Japanese selvedge denim in a slim taper, built to break in and age with wear.',
    images: ['https://images.pexels.com/photos/16069736/pexels-photo-16069736.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/4258605/pexels-photo-4258605.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['30','32','34','36','38'], stock: 32, isFeatured: false, isTrending: true, rating: 4.3, numReviews: 2,
    reviews: [{name:'Rohan K.',rating:4,comment:'Great quality, runs slightly large so consider sizing down.'}] },
  { _id: 'm4', name: 'Oxford Cotton Shirt', brand: 'Van Heusen', category: 'men', price: 1799, discountPercent: 0,
    description: 'A breathable oxford weave shirt with a clean point collar, equally at home tucked or worn open.',
    images: ['https://images.pexels.com/photos/15849965/pexels-photo-15849965.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/7489793/pexels-photo-7489793.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['S','M','L','XL'], stock: 55, isFeatured: false, isTrending: false, rating: 4.6, numReviews: 1,
    reviews: [{name:'Ananya R.',rating:5,comment:'Fit is exactly as described, fabric feels genuinely premium.'}] },
  { _id: 'm5', name: 'Leather Chelsea Boots', brand: 'Red Tape', category: 'men', price: 4499, discountPercent: 10,
    description: 'Full-grain leather Chelsea boots with an elastic side panel and a stacked leather heel.',
    images: ['https://images.pexels.com/photos/9323599/pexels-photo-9323599.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/9323599/pexels-photo-9323599.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['40','41','42','43','44','45'], stock: 18, isFeatured: true, isTrending: false, rating: 4.8, numReviews: 3,
    reviews: [{name:'Priya S.',rating:5,comment:'Ordered twice now, stitching and finish are consistently excellent.'}] },
  { _id: 'm6', name: 'Technical Shell Jacket', brand: 'Wildcraft', category: 'men', price: 3999, discountPercent: 0,
    description: 'A packable, weatherproof shell with taped seams for unpredictable city weather.',
    images: ['https://images.pexels.com/photos/18720773/pexels-photo-18720773.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/2229712/pexels-photo-2229712.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['S','M','L','XL'], stock: 27, isFeatured: false, isTrending: true, rating: 4.4, numReviews: 2,
    reviews: [{name:'Ananya R.',rating:5,comment:'Fit is exactly as described, fabric feels genuinely premium.'}] },

  { _id: 'w1', name: 'Silk Wrap Midi Dress', brand: 'Global Desi', category: 'women', price: 5499, discountPercent: 20,
    description: 'A fluid silk midi with a self-tie waist, cut to move with you from desk to dinner.',
    images: ['https://images.pexels.com/photos/20332986/pexels-photo-20332986.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/20332974/pexels-photo-20332974.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['XS','S','M','L'], stock: 22, isFeatured: true, isTrending: true, rating: 4.9, numReviews: 3,
    reviews: [{name:'Ananya R.',rating:5,comment:'Fit is exactly as described, fabric feels genuinely premium.'}] },
  { _id: 'w2', name: 'Cropped Tailored Blazer', brand: 'Zara', category: 'women', price: 4999, discountPercent: 0,
    description: 'A sharply tailored blazer with a cropped body and structured shoulder for a modern silhouette.',
    images: ['https://images.pexels.com/photos/10228177/pexels-photo-10228177.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/8368060/pexels-photo-8368060.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['XS','S','M','L','XL'], stock: 30, isFeatured: true, isTrending: false, rating: 4.6, numReviews: 2,
    reviews: [{name:'Rohan K.',rating:4,comment:'Great quality, runs slightly large so consider sizing down.'}] },
  { _id: 'w3', name: 'High-Rise Wide Trousers', brand: 'W for Woman', category: 'women', price: 2299, discountPercent: 0,
    description: 'Fluid wide-leg trousers with a high rise and a fully lined waistband for a clean drape.',
    images: ['https://images.pexels.com/photos/7959652/pexels-photo-7959652.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/7959652/pexels-photo-7959652.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['XS','S','M','L'], stock: 38, isFeatured: false, isTrending: false, rating: 4.2, numReviews: 1,
    reviews: [{name:'Priya S.',rating:5,comment:'Ordered twice now, stitching and finish are consistently excellent.'}] },
  { _id: 'w4', name: 'Ribbed Knit Midi Skirt', brand: 'AND', category: 'women', price: 1899, discountPercent: 0,
    description: 'A body-skimming ribbed knit skirt that pairs equally well with boots or heels.',
    images: ['https://images.pexels.com/photos/15345385/pexels-photo-15345385.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/15345385/pexels-photo-15345385.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['XS','S','M','L'], stock: 33, isFeatured: false, isTrending: true, rating: 4.5, numReviews: 2,
    reviews: [{name:'Rohan K.',rating:4,comment:'Great quality, runs slightly large so consider sizing down.'}] },
  { _id: 'w5', name: 'Leather Ankle-Strap Heels', brand: 'Metro Shoes', category: 'women', price: 3499, discountPercent: 12,
    description: 'A refined kitten heel in supple leather with a delicate ankle strap.',
    images: ['https://images.pexels.com/photos/8368060/pexels-photo-8368060.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/8368060/pexels-photo-8368060.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['36','37','38','39','40'], stock: 20, isFeatured: false, isTrending: false, rating: 4.3, numReviews: 1,
    reviews: [{name:'Ananya R.',rating:5,comment:'Fit is exactly as described, fabric feels genuinely premium.'}] },
  { _id: 'w6', name: 'Oversized Cashmere Scarf-Coat', brand: 'FabIndia', category: 'women', price: 7499, discountPercent: 0,
    description: 'An oversized cashmere-blend coat designed to be worn open, like a wearable scarf.',
    images: ['https://images.pexels.com/photos/9968481/pexels-photo-9968481.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/9968530/pexels-photo-9968530.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['XS/S','M/L'], stock: 15, isFeatured: true, isTrending: false, rating: 4.8, numReviews: 2,
    reviews: [{name:'Priya S.',rating:5,comment:'Ordered twice now, stitching and finish are consistently excellent.'}] },

  { _id: 'k1', name: 'Organic Cotton Hoodie', brand: 'Mothercare', category: 'kids', price: 1299, discountPercent: 0,
    description: 'A soft organic cotton hoodie with a kangaroo pocket, built for everyday play.',
    images: ['https://images.pexels.com/photos/15290406/pexels-photo-15290406.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/10495939/pexels-photo-10495939.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['2-3Y','4-5Y','6-7Y','8-9Y'], stock: 45, isFeatured: true, isTrending: false, rating: 4.6, numReviews: 2,
    reviews: [{name:'Rohan K.',rating:4,comment:'Great quality, runs slightly large so consider sizing down.'}] },
  { _id: 'k2', name: 'Corduroy Dungarees', brand: 'Gini & Jony', category: 'kids', price: 1499, discountPercent: 0,
    description: 'Durable corduroy dungarees with adjustable straps and reinforced knees.',
    images: ['https://images.pexels.com/photos/27177130/pexels-photo-27177130.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/27177130/pexels-photo-27177130.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['1-2Y','2-3Y','4-5Y'], stock: 28, isFeatured: false, isTrending: false, rating: 4.4, numReviews: 1,
    reviews: [{name:'Ananya R.',rating:5,comment:'Fit is exactly as described, fabric feels genuinely premium.'}] },
  { _id: 'k3', name: 'Printed Cotton Dress', brand: 'H&M Kids', category: 'kids', price: 1099, discountPercent: 10,
    description: 'A lightweight cotton dress with a hand-drawn print and a twirl-friendly hem.',
    images: ['https://images.pexels.com/photos/18649978/pexels-photo-18649978.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'https://images.pexels.com/photos/18511343/pexels-photo-18511343.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop'],
    sizes: ['2-3Y','4-5Y','6-7Y'], stock: 26, isFeatured: false, isTrending: true, rating: 4.7, numReviews: 2,
    reviews: [{name:'Priya S.',rating:5,comment:'Ordered twice now, stitching and finish are consistently excellent.'}] },
];
